/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Wed Sep 14 17:41:30 2022. */

#include "comm.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t DATA_CmdParam_fields[2] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, STATIC  , FIRST, DATA_CmdParam, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t DATA_FileInfo_fields[7] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, DATA_FileInfo, file_name, file_name, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, DATA_FileInfo, file_size, file_name, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, DATA_FileInfo, block_size, file_size, 0),
    PB_FIELD(  4, STRING  , REQUIRED, STATIC  , OTHER, DATA_FileInfo, version_hw, block_size, 0),
    PB_FIELD(  5, STRING  , REQUIRED, STATIC  , OTHER, DATA_FileInfo, version_sw, version_hw, 0),
    PB_FIELD(  6, UINT32  , REQUIRED, STATIC  , OTHER, DATA_FileInfo, encrype, version_sw, 0),
    PB_LAST_FIELD
};

const pb_field_t DATA_Block_fields[5] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, DATA_Block, block_amount, block_amount, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, DATA_Block, block_id, block_amount, 0),
    PB_FIELD(  3, BYTES   , REQUIRED, STATIC  , OTHER, DATA_Block, data, block_id, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, DATA_Block, checksum, data, 0),
    PB_LAST_FIELD
};

const pb_field_t DATA_Echo_fields[3] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, DATA_Echo, errcode, errcode, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, DATA_Echo, block_id, errcode, 0),
    PB_LAST_FIELD
};

const pb_field_t DATA_CAN_Filter_fields[2] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, FIRST, DATA_CAN_Filter, ids, ids, 0),
    PB_LAST_FIELD
};

const pb_field_t DATA_NWStat_fields[7] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, DATA_NWStat, eMode, eMode, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, DATA_NWStat, csq, eMode, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, DATA_NWStat, anteStat, csq, 0),
    PB_FIELD(  4, UENUM   , REQUIRED, STATIC  , OTHER, DATA_NWStat, eDevStat, anteStat, 0),
    PB_FIELD(  5, UENUM   , REQUIRED, STATIC  , OTHER, DATA_NWStat, eNetStat, eDevStat, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, DATA_NWStat, diagRet, eNetStat, 0),
    PB_LAST_FIELD
};

const pb_field_t TICK_fields[8] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, TICK, year, year, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, TICK, month, year, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, TICK, day, month, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, TICK, hour, day, 0),
    PB_FIELD(  5, UINT32  , REQUIRED, STATIC  , OTHER, TICK, min, hour, 0),
    PB_FIELD(  6, UINT32  , REQUIRED, STATIC  , OTHER, TICK, sec, min, 0),
    PB_FIELD(  7, UINT32  , REQUIRED, STATIC  , OTHER, TICK, msec, sec, 0),
    PB_LAST_FIELD
};

const pb_field_t CAN_FRAME_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, CAN_FRAME, id, id, 0),
    PB_FIELD(  2, BYTES   , REQUIRED, STATIC  , OTHER, CAN_FRAME, data, id, 0),
    PB_LAST_FIELD
};

const pb_field_t DATA_CANFrames_fields[3] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, DATA_CANFrames, tick, tick, &TICK_fields),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, DATA_CANFrames, frames, tick, &CAN_FRAME_fields),
    PB_LAST_FIELD
};

const pb_field_t DATA_CANData_fields[2] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, STATIC  , FIRST, DATA_CANData, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t DATA_GPSInfo_fields[7] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, DATA_GPSInfo, valid, valid, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, DATA_GPSInfo, longitude, valid, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, DATA_GPSInfo, latitude, longitude, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, DATA_GPSInfo, speed, latitude, 0),
    PB_FIELD(  5, UINT32  , REQUIRED, STATIC  , OTHER, DATA_GPSInfo, angle, speed, 0),
    PB_FIELD(  6, MESSAGE , REQUIRED, STATIC  , OTHER, DATA_GPSInfo, tick, angle, &TICK_fields),
    PB_LAST_FIELD
};

const pb_field_t DATA_ModemInfo_fields[12] = {
    PB_FIELD(  1, UENUM   , OPTIONAL, STATIC  , FIRST, DATA_ModemInfo, eMode, eMode, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, DATA_ModemInfo, csq, eMode, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, DATA_ModemInfo, anteStat, csq, 0),
    PB_FIELD(  4, UENUM   , OPTIONAL, STATIC  , OTHER, DATA_ModemInfo, eDevStat, anteStat, 0),
    PB_FIELD(  5, UENUM   , OPTIONAL, STATIC  , OTHER, DATA_ModemInfo, eNetStat, eDevStat, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, DATA_ModemInfo, diagRet, eNetStat, 0),
    PB_FIELD(  7, MESSAGE , OPTIONAL, STATIC  , OTHER, DATA_ModemInfo, gps_info, diagRet, &DATA_GPSInfo_fields),
    PB_FIELD(  8, UENUM   , OPTIONAL, STATIC  , OTHER, DATA_ModemInfo, eLPMStat, gps_info, 0),
    PB_FIELD(  9, UENUM   , OPTIONAL, STATIC  , OTHER, DATA_ModemInfo, eOTAStat, eLPMStat, 0),
    PB_FIELD( 10, STRING  , OPTIONAL, STATIC  , OTHER, DATA_ModemInfo, iccid, eOTAStat, 0),
    PB_FIELD( 11, STRING  , OPTIONAL, STATIC  , OTHER, DATA_ModemInfo, version, iccid, 0),
    PB_LAST_FIELD
};

const pb_field_t DATA_MCUInfo_fields[7] = {
    PB_FIELD(  1, UENUM   , OPTIONAL, STATIC  , FIRST, DATA_MCUInfo, power_mode, power_mode, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, DATA_MCUInfo, battery_cap, power_mode, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, DATA_MCUInfo, sleep_ctrl, battery_cap, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, DATA_MCUInfo, sleep_ctrl_force, sleep_ctrl, 0),
    PB_FIELD(  5, STRING  , OPTIONAL, STATIC  , OTHER, DATA_MCUInfo, version, sleep_ctrl_force, 0),
    PB_FIELD(  6, STRING  , OPTIONAL, STATIC  , OTHER, DATA_MCUInfo, sn, version, 0),
    PB_LAST_FIELD
};

const pb_field_t DATA_RealInfo_fields[4] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, DATA_RealInfo, warning, warning, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, DATA_RealInfo, upl, warning, 0),
    PB_FIELD(  3, BYTES   , REQUIRED, STATIC  , OTHER, DATA_RealInfo, data, upl, 0),
    PB_LAST_FIELD
};

const pb_field_t DATA_SysMode_fields[2] = {
    PB_FIELD(  1, BOOL    , REQUIRED, STATIC  , FIRST, DATA_SysMode, gb_mode, gb_mode, 0),
    PB_LAST_FIELD
};

const pb_field_t DATA_VehLogin_fields[8] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, DATA_VehLogin, vin, vin, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, DATA_VehLogin, tin, vin, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, DATA_VehLogin, batteryPackNum, tin, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, DATA_VehLogin, batteryPackCodeLen, batteryPackNum, 0),
    PB_FIELD(  5, STRING  , REQUIRED, STATIC  , OTHER, DATA_VehLogin, batteryPackCodes, batteryPackCodeLen, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, DATA_VehLogin, vehModel, batteryPackCodes, 0),
    PB_FIELD(  7, UINT32  , OPTIONAL, STATIC  , OTHER, DATA_VehLogin, swVer, vehModel, 0),
    PB_LAST_FIELD
};

const pb_field_t ECU_UPGRADE_STATUS_fields[5] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, ECU_UPGRADE_STATUS, id, id, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, ECU_UPGRADE_STATUS, ota_state, id, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, ECU_UPGRADE_STATUS, progress, ota_state, 0),
    PB_FIELD(  4, BOOL    , OPTIONAL, STATIC  , OTHER, ECU_UPGRADE_STATUS, do_upgrade, progress, 0),
    PB_LAST_FIELD
};

const pb_field_t COMM_Msg_fields[17] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, COMM_Msg, session_id, session_id, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, COMM_Msg, msg_id, session_id, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, COMM_Msg, ack_flag, msg_id, 0),
    PB_FIELD(  4, UENUM   , REQUIRED, STATIC  , OTHER, COMM_Msg, target, ack_flag, 0),
    PB_ONEOF_FIELD(data,   5, MESSAGE , ONEOF, STATIC  , OTHER, COMM_Msg, cmd_param, target, &DATA_CmdParam_fields),
    PB_ONEOF_FIELD(data,   6, MESSAGE , ONEOF, STATIC  , UNION, COMM_Msg, file_info, target, &DATA_FileInfo_fields),
    PB_ONEOF_FIELD(data,   7, MESSAGE , ONEOF, STATIC  , UNION, COMM_Msg, block, target, &DATA_Block_fields),
    PB_ONEOF_FIELD(data,   8, MESSAGE , ONEOF, STATIC  , UNION, COMM_Msg, echo, target, &DATA_Echo_fields),
    PB_ONEOF_FIELD(data,   9, MESSAGE , ONEOF, STATIC  , UNION, COMM_Msg, modem_info, target, &DATA_ModemInfo_fields),
    PB_ONEOF_FIELD(data,  10, MESSAGE , ONEOF, STATIC  , UNION, COMM_Msg, mcu_info, target, &DATA_MCUInfo_fields),
    PB_ONEOF_FIELD(data,  11, MESSAGE , ONEOF, STATIC  , UNION, COMM_Msg, real_info, target, &DATA_RealInfo_fields),
    PB_ONEOF_FIELD(data,  12, MESSAGE , ONEOF, STATIC  , UNION, COMM_Msg, can_data, target, &DATA_CANData_fields),
    PB_ONEOF_FIELD(data,  13, MESSAGE , ONEOF, STATIC  , UNION, COMM_Msg, can_filters, target, &DATA_CAN_Filter_fields),
    PB_ONEOF_FIELD(data,  14, MESSAGE , ONEOF, STATIC  , UNION, COMM_Msg, sys_mode, target, &DATA_SysMode_fields),
    PB_ONEOF_FIELD(data,  15, MESSAGE , ONEOF, STATIC  , UNION, COMM_Msg, veh_login, target, &DATA_VehLogin_fields),
    PB_FIELD( 16, UENUM   , OPTIONAL, STATIC  , OTHER, COMM_Msg, src, data.veh_login, 0),
    PB_LAST_FIELD
};

const pb_field_t OTA_File_fullinfo_fields[3] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, OTA_File_fullinfo, headinfo, headinfo, &DATA_FileInfo_fields),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, OTA_File_fullinfo, blocks, headinfo, &DATA_Block_fields),
    PB_LAST_FIELD
};

const pb_field_t OTA_MetaInfo_fields[5] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, OTA_MetaInfo, mcu_metainfo, mcu_metainfo, &DATA_FileInfo_fields),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, OTA_MetaInfo, firm_metainfo, mcu_metainfo, &DATA_FileInfo_fields),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, OTA_MetaInfo, cpu_metainfo, firm_metainfo, &DATA_FileInfo_fields),
    PB_FIELD(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, OTA_MetaInfo, ble_metainfo, cpu_metainfo, &DATA_FileInfo_fields),
    PB_LAST_FIELD
};






















/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(DATA_CmdParam, data) < 65536 && pb_membersize(DATA_Block, data) < 65536 && pb_membersize(DATA_CANFrames, tick) < 65536 && pb_membersize(DATA_CANData, data) < 65536 && pb_membersize(DATA_GPSInfo, tick) < 65536 && pb_membersize(DATA_ModemInfo, gps_info) < 65536 && pb_membersize(DATA_RealInfo, data) < 65536 && pb_membersize(COMM_Msg, data.cmd_param) < 65536 && pb_membersize(COMM_Msg, data.file_info) < 65536 && pb_membersize(COMM_Msg, data.block) < 65536 && pb_membersize(COMM_Msg, data.echo) < 65536 && pb_membersize(COMM_Msg, data.modem_info) < 65536 && pb_membersize(COMM_Msg, data.mcu_info) < 65536 && pb_membersize(COMM_Msg, data.real_info) < 65536 && pb_membersize(COMM_Msg, data.can_data) < 65536 && pb_membersize(COMM_Msg, data.can_filters) < 65536 && pb_membersize(COMM_Msg, data.sys_mode) < 65536 && pb_membersize(COMM_Msg, data.veh_login) < 65536 && pb_membersize(OTA_File_fullinfo, headinfo) < 65536 && pb_membersize(OTA_MetaInfo, mcu_metainfo) < 65536 && pb_membersize(OTA_MetaInfo, firm_metainfo) < 65536 && pb_membersize(OTA_MetaInfo, cpu_metainfo) < 65536 && pb_membersize(OTA_MetaInfo, ble_metainfo) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_DATA_CmdParam_DATA_FileInfo_DATA_Block_DATA_Echo_DATA_CAN_Filter_DATA_NWStat_TICK_CAN_FRAME_DATA_CANFrames_DATA_CANData_DATA_GPSInfo_DATA_ModemInfo_DATA_MCUInfo_DATA_RealInfo_DATA_SysMode_DATA_VehLogin_ECU_UPGRADE_STATUS_COMM_Msg_OTA_File_fullinfo_OTA_MetaInfo)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for DATA_RealInfo.data is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
